apiVersion: v1
kind: Pod
metadata:
  name: sample-ephemeral-storage
spec:
  containers:
    - name: nginx-container
      image: nginx:1.17
      resources:
        requests:
          ephemeral-storage: "128Mi"
        limits:
          ephemeral-storage: "256Mi"
