apiVersion: v1
kind: Pod
metadata:
  name: sample-env
  label:
    sample-app
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    env:
  - name: MAX_CONNECTION
    value: "100"
  - name: TZ
    value: Asia/Seoul
